name: publish ccx and make tag

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Create Release Asset
        shell: bash
        run: |
            cd $GITHUB_WORKSPACE
            npm i
            npm run publish
            node build-script/pack-ccx.mjs --version ${{ github.event.inputs.tag_name }}
              
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v${{ github.event.inputs.tag_name }}
            release_name: v${{ github.event.inputs.tag_name }}
            draft: true
            prerelease: false

      - name: Upload ZIP
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./Auto.Photoshop.SD.plugin_v${{ github.event.inputs.tag_name }}.zip
            asset_name: Auto.Photoshop.SD.plugin_v${{ github.event.inputs.tag_name }}.zip
            asset_content_type: application/zip
            
      - name: Upload CCX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Auto.Photoshop.SD.plugin_v${{ github.event.inputs.tag_name }}.ccx
          asset_name: Auto.Photoshop.SD.plugin_v${{ github.event.inputs.tag_name }}.ccx
          asset_content_type: application/zip