on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
#           - name: wiki-safe
#             run: |
#                 git config --global --add safe.directory /wiki
          - uses: actions/checkout@master
          - name: Sync Wiki
#             uses: joeizzard/action-wiki-sync@master
            uses: AbdullahAlfaraj/ghaction-wiki-sync@master

        
            with:
                username: AbdullahAlfaraj
                access_token: ${{ secrets.WIKI_ACTION_TOKEN }}
                wiki_folder: wiki
                commit_username: 'AbdullahAlfaraj '
                commit_email: '7842232+AbdullahAlfaraj@users.noreply.github.com'
                commit_message: 'action: wiki sync'
            
